// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package hobby

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// HobbyClient is the client API for Hobby service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HobbyClient interface {
	Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
	Search2(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
}

type hobbyClient struct {
	cc grpc.ClientConnInterface
}

func NewHobbyClient(cc grpc.ClientConnInterface) HobbyClient {
	return &hobbyClient{cc}
}

func (c *hobbyClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, "/proto.Hobby/Search", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hobbyClient) Search2(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, "/proto.Hobby/Search2", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HobbyServer is the server API for Hobby service.
// All implementations must embed UnimplementedHobbyServer
// for forward compatibility
type HobbyServer interface {
	Search(context.Context, *SearchRequest) (*SearchResponse, error)
	Search2(context.Context, *SearchRequest) (*SearchResponse, error)
	mustEmbedUnimplementedHobbyServer()
}

// UnimplementedHobbyServer must be embedded to have forward compatible implementations.
type UnimplementedHobbyServer struct {
}

func (UnimplementedHobbyServer) Search(context.Context, *SearchRequest) (*SearchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Search not implemented")
}
func (UnimplementedHobbyServer) Search2(context.Context, *SearchRequest) (*SearchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Search2 not implemented")
}
func (UnimplementedHobbyServer) mustEmbedUnimplementedHobbyServer() {}

// UnsafeHobbyServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HobbyServer will
// result in compilation errors.
type UnsafeHobbyServer interface {
	mustEmbedUnimplementedHobbyServer()
}

func RegisterHobbyServer(s grpc.ServiceRegistrar, srv HobbyServer) {
	s.RegisterService(&Hobby_ServiceDesc, srv)
}

func _Hobby_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HobbyServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Hobby/Search",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HobbyServer).Search(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hobby_Search2_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HobbyServer).Search2(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Hobby/Search2",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HobbyServer).Search2(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Hobby_ServiceDesc is the grpc.ServiceDesc for Hobby service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Hobby_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Hobby",
	HandlerType: (*HobbyServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Search",
			Handler:    _Hobby_Search_Handler,
		},
		{
			MethodName: "Search2",
			Handler:    _Hobby_Search2_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hobby.proto",
}
